[package]
name = "tos_directory"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1.0.56"
chrono = "0.4.19"
fern = "0.6.0"
log = "0.4.16"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
tera = "1"
